# Generated by Django 4.2.3 on 2023-07-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="engine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("Horse_power", models.CharField(max_length=30)),
                ("fuel_type", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name="showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("pic", models.ImageField(upload_to="")),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("pic", models.ImageField(upload_to="")),
                ("Role", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=13)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="showroom.showroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="")),
                ("release_date", models.DateField()),
                ("price", models.IntegerField()),
                (
                    "engine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model",
                        to="showroom.engine",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(related_name="model", to="showroom.feature"),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model",
                        to="showroom.showroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "chessis_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car",
                        to="showroom.model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="")),
                ("founder", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=14)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand",
                        to="showroom.showroom",
                    ),
                ),
            ],
        ),
    ]
