# Generated by Django 4.2.3 on 2023-07-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_alter_model_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="engine_number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "name",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_no",
                        to="showroom.engine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="engine_number",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="showroom.engine_number",
            ),
        ),
    ]
