# Generated by Django 4.2.3 on 2023-07-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0005_customer_stock_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="model_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale",
                to="showroom.model",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
