# Generated by Django 4.2.3 on 2023-07-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_sale_model_name_alter_feature_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="engine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="showroom.engine",
            ),
        ),
    ]
