# Generated by Django 4.2.3 on 2023-07-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_alter_model_engine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engine_number",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engine_no",
                to="showroom.engine",
            ),
        ),
    ]
