# Generated by Django 4.2.3 on 2023-07-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0009_alter_customer_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car",
                to="showroom.model",
            ),
        ),
    ]
