# Generated by Django 4.2.3 on 2023-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0010_alter_car_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="quantity_in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
