# Generated by Django 4.2.3 on 2023-07-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0011_model_quantity_in_stock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="stock",
        ),
    ]
